 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stresses", type: :request do
  # Stress. As you add validations to Stress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Stress.create! valid_attributes
      get stresses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stress = Stress.create! valid_attributes
      get stress_url(stress)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stress_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      stress = Stress.create! valid_attributes
      get edit_stress_url(stress)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Stress" do
        expect {
          post stresses_url, params: { stress: valid_attributes }
        }.to change(Stress, :count).by(1)
      end

      it "redirects to the created stress" do
        post stresses_url, params: { stress: valid_attributes }
        expect(response).to redirect_to(stress_url(Stress.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Stress" do
        expect {
          post stresses_url, params: { stress: invalid_attributes }
        }.to change(Stress, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post stresses_url, params: { stress: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stress" do
        stress = Stress.create! valid_attributes
        patch stress_url(stress), params: { stress: new_attributes }
        stress.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the stress" do
        stress = Stress.create! valid_attributes
        patch stress_url(stress), params: { stress: new_attributes }
        stress.reload
        expect(response).to redirect_to(stress_url(stress))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        stress = Stress.create! valid_attributes
        patch stress_url(stress), params: { stress: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stress" do
      stress = Stress.create! valid_attributes
      expect {
        delete stress_url(stress)
      }.to change(Stress, :count).by(-1)
    end

    it "redirects to the stresses list" do
      stress = Stress.create! valid_attributes
      delete stress_url(stress)
      expect(response).to redirect_to(stresses_url)
    end
  end
end
